vpn_service/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),


    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.UserSiteCreateView.as_view(), name='create'),
    
    path('proxy/<str:user_site_name>/<path:path>', views.ProxyView.as_view(), name='proxy'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserSite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.name

class TrafficStats(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    site = models.ForeignKey(UserSite, on_delete=models.CASCADE)
    visits = models.IntegerField(default=0)
    data_transferred = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.user.username} - {self.site.name}"

app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from app.models import UserSite

class SignUpForm(forms.ModelForm):
    check_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ("email", "username","password", "check_password")
        widgets = {
            "password": forms.widgets.PasswordInput(),
        }

    def clean_check_password(self):
        if self.cleaned_data["password"] != self.cleaned_data["check_password"]:
            raise forms.ValidationError("Invalid Password")
        else:
            return self.cleaned_data["password"]

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user
    
    
class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class UserSiteForm(forms.ModelForm):
    class Meta:
        model = UserSite
        fields = ('name', 'url',)

app/views.py
from django.shortcuts import render, redirect
from django.views import View 
from django.views.generic import TemplateView, FormView, CreateView
from app.models import UserSite, TrafficStats
from bs4 import BeautifulSoup
import requests
from django.http import HttpResponse
from app.forms import SignUpForm, UpdateProfileForm, UserSiteForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class SignUpView(FormView):
    template_name = "signup.html"
    form_class = SignUpForm
    success_url = "/login/"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["traffic_stats"] = TrafficStats.objects.filter(user=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        form = UpdateProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
        return self.render_to_response(self.get_context_data(form=form))
    

class UserSiteCreateView(CreateView):
    model = UserSite
    form_class = UserSiteForm
    template_name = 'user_site_create.html'  
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)
        
    
class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["user_links"] = UserSite.objects.filter(user=self.request.user).all()
        return context
    

class ProxyView(View):
    
    def get(self, request, user_site_name, path):
        user_site = UserSite.objects.get(user=request.user, name=user_site_name)
        
        url = f'{user_site.url}/{path}'
        response = requests.get(url)
        content = response.content
        
        soup = BeautifulSoup(content, 'html.parser')
        for link in soup.find_all('a'):
            if 'href' in link.attrs:
                href = link.attrs['href']
                if not href.startswith('http'): 
                    link.attrs['href'] = f'/proxy/{user_site_name}/{href}'
        
        modified_content = str(soup)

        stats, created = TrafficStats.objects.get_or_create(
            user=request.user,
            site=user_site,
            defaults={'visits': 1, 'data_transferred': len(content)}
        )
        if not created:
            stats.visits += 1
            stats.data_transferred += len(content)
            stats.save()
        
        return HttpResponse(modified_content)
    

     

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Website</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .navbar-nav {
            margin: auto;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <span class="navbar-text navbar-brand">
            Welcome, {{ user.username }}
        </span>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Index</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Create Link</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<main>
    {% block content %}
    {% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    {% if user %}
        <h2 class="text-center mb-4">Your Links</h2>
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% for item in user_links %}
                    <div class="card mb-3 text-center">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <p class="card-text">{{ item.url }}</p>
                            <a href="/proxy/{{ item.name }}/home" class="btn btn-primary">Go</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>
{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5 d-flex justify-content-center align-items-center">
    <div class="card text-center">
        <div class="card-body">
            <h2 class="card-title">Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" id="username" name="username" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" id="password" name="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">User Profile</h1>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>User Data</h2>
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>

            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">New Username:</label>
                    <input type="text" id="username" name="username" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Change</button>
            </form>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-8">
            <h2>Statistics</h2>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Website</th>
                        <th scope="col">Visits</th>
                        <th scope="col">Data Transferred</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stat in traffic_stats %}
                    <tr>
                        <td>{{ stat.site }}</td>
                        <td>{{ stat.visits }}</td>
                        <td>{{ stat.data_transferred }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5 d-flex justify-content-center align-items-center" >
    <div class="card text-center">
        <div class="card-body">
            <h2 class="card-title">SignUp</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username" class="form-label">Username:</label>
                    <input type="text" id="id_username" name="username" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email address:</label>
                    <input type="email" id="id_email" name="email" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Password:</label>
                    <input type="password" id="id_password" name="password" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="id_check_password" class="form-label">Confirm Password:</label>
                    <input type="password" id="id_check_password" name="check_password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">SignUp</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/user_site_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Create New Link</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="id_name" class="form-label">Link Name:</label>
                  <input type="text" id="id_name" name="name" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="id_url" class="form-label">Link URL:</label>
                    <input type="url" id="id_url" name="url" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}